---
stages:
  - test_puppet4
  - test_puppet5
  - test_puppet6

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install --without system_tests

rubocop-puppet4:
  stage: test_puppet4
  image: ruby:2.3
  script:
    - bundle exec rake rubocop

syntax-puppet4:
  stage: test_puppet4
  image: ruby:2.3
  script:
    - bundle exec rake syntax lint

metadata-puppet4:
  stage: test_puppet4
  image: ruby:2.3
  script:
    - bundle exec rake metadata_lint

rspec-puppet-puppet4:
  stage: test_puppet4
  image: ruby:2.3
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
  script:
    - bundle update
    - bundle exec rake spec

rubocop-puppet5:
  stage: test_puppet5
  image: ruby:2.4
  script:
    - bundle exec rake rubocop

syntax-puppet5:
  stage: test_puppet5
  image: ruby:2.4
  script:
    - bundle exec rake syntax lint

metadata-puppet5:
  stage: test_puppet5
  image: ruby:2.4
  script:
    - bundle exec rake metadata_lint

rspec-puppet-puppet5:
  stage: test_puppet5
  image: ruby:2.4
  variables:
    PUPPET_GEM_VERSION: ~> 5.0
  script:
    - bundle update
    - bundle exec rake spec

rubocop-puppet6:
  stage: test_puppet6
  image: ruby:2.5
  script:
    - bundle exec rake rubocop

syntax-puppet6:
  stage: test_puppet6
  image: ruby:2.5
  script:
    - bundle exec rake syntax lint

metadata-puppet6:
  stage: test_puppet6
  image: ruby:2.5
  script:
    - bundle exec rake metadata_lint

rspec-puppet-puppet6:
  stage: test_puppet6
  image: ruby:2.5
  variables:
    PUPPET_GEM_VERSION: ~> 6.0
  script:
    - bundle update
    - bundle exec rake spec
